---
# tasks file for /etc/ansible/roles/syslog

- name: install syslog-ng
  yum:
    name: syslog-ng
    state: present
  notify:
  - start syslog-ng

-name: "Configuration of syslog-ng"
  template:
    backup: yes
    src: '{{syslog_ng_template}}'
    dest: '{{syslog_ng_config_file}}'
  notify:
  -reload syslog-ng  